<a href="https://colab.research.google.com/github/ZALER-01/AngularPractice/blob/main/Maintaing_py.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# New Section

https://www.superdatascience.com/machine-learning
 challenge@superdatascience.com
 # Feature Sacling always applies on columns

 Normalization
 x' = x - x min / x max - x min

 suppose we have a dataset

 Blue  $70000 45
 Red   $60000 44
 Purple $52000 40
 Step-by-Step CalculationFeature 1: Numerical Values
 ($70,000, $60,000, $52,000)
 $x_{min}$: $52,000$$x_{max}$: $70,000$Range ($x_{max} - x_{min}$): $18,000$Blue: $\frac{70,000 - 52,000}{18,000} = \frac{18,000}{18,000} = \mathbf{1.0}$Red: $\frac{60,000 - 52,000}{18,000} = \frac{8,000}{18,000} \approx \mathbf{0.444}$Purple: $\frac{52,000 - 52,000}{18,000} = \frac{0}{18,000} = \mathbf{0.0}$Feature 2: Age/Count (45, 44, 40)$x_{min}$: $40$$x_{max}$: $45$Range ($x_{max} - x_{min}$): $5$Blue: $\frac{45 - 40}{5} = \frac{5}{5} = \mathbf{1.0}$Red: $\frac{44 - 40}{5} = \frac{4}{5} = \mathbf{0.8}$Purple: $\frac{40 - 40}{5} = \frac{0}{5} = \mathbf{0.0}$Normalized DatasetAfter applying the formula, your dataset is now on a uniform scale:ColorFeature 1 (Normalized)Feature 2 (Normalized)Blue1.0001.000Red0.4440.800Purple0.0000.000


In [12]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt


df = pd.read_csv(r'/content/Data.csv')
print(df)
x = df.iloc[: ,: -1].values
print(x)
# it is taking all the range except last column
y = df.iloc[:, -1].values
print(y)

   Country   Age   Salary Purchased
0   France  44.0  72000.0        No
1    Spain  27.0  48000.0       Yes
2  Germany  30.0  54000.0        No
3    Spain  38.0  61000.0        No
4  Germany  40.0      NaN       Yes
5   France  35.0  58000.0       Yes
6    Spain   NaN  52000.0        No
7   France  48.0  79000.0       Yes
8  Germany  50.0  83000.0        No
9   France  37.0  67000.0       Yes
[['France' 44.0 72000.0]
 ['Spain' 27.0 48000.0]
 ['Germany' 30.0 54000.0]
 ['Spain' 38.0 61000.0]
 ['Germany' 40.0 nan]
 ['France' 35.0 58000.0]
 ['Spain' nan 52000.0]
 ['France' 48.0 79000.0]
 ['Germany' 50.0 83000.0]
 ['France' 37.0 67000.0]]
['No' 'Yes' 'No' 'No' 'Yes' 'Yes' 'No' 'Yes' 'No' 'Yes']


In [19]:
import numpy as np
from sklearn.impute import SimpleImputer

# 1. Initialize the imputer (fixed the double '=' and added np import)
imputer = SimpleImputer(missing_values=np.nan, strategy='mean')

# 2. Fit the imputer to the specific columns (indices 1 and 2)
imputer.fit(x[:, 1:3])

# 3. Transform the data and assign it back to the array
x[:, 1:3] = imputer.transform(x[:, 1:3])

print(x)
print(y)




[['France' 44.0 72000.0]
 ['Spain' 27.0 48000.0]
 ['Germany' 30.0 54000.0]
 ['Spain' 38.0 61000.0]
 ['Germany' 40.0 63777.77777777778]
 ['France' 35.0 58000.0]
 ['Spain' 38.77777777777778 52000.0]
 ['France' 48.0 79000.0]
 ['Germany' 50.0 83000.0]
 ['France' 37.0 67000.0]]
['No' 'Yes' 'No' 'No' 'Yes' 'Yes' 'No' 'Yes' 'No' 'Yes']


In [21]:
import numpy as np
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder

# 1. Define the transformer
# We pass a list containing a tuple: (name, object, column_indices)
ct = ColumnTransformer(
    transformers=[('encoder', OneHotEncoder(), [0])],
    remainder='passthrough'
)

# 2. Fit and transform your data (and convert to a numpy array)
x = np.array(ct.fit_transform(x))


In [22]:
print(x)

[[0.0 1.0 0.0 0.0 44.0 72000.0]
 [1.0 0.0 0.0 1.0 27.0 48000.0]
 [1.0 0.0 1.0 0.0 30.0 54000.0]
 [1.0 0.0 0.0 1.0 38.0 61000.0]
 [1.0 0.0 1.0 0.0 40.0 63777.77777777778]
 [0.0 1.0 0.0 0.0 35.0 58000.0]
 [1.0 0.0 0.0 1.0 38.77777777777778 52000.0]
 [0.0 1.0 0.0 0.0 48.0 79000.0]
 [1.0 0.0 1.0 0.0 50.0 83000.0]
 [0.0 1.0 0.0 0.0 37.0 67000.0]]


In [24]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y = le.fit_transform(y)
print(y)


[0 1 0 0 1 1 0 1 0 1]
